## Section 2: Clean & Tidy Data

marimo run m2w1_marimo.py
marimo run m2w2_marimo.py

In [33]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

### Exercise 1: Dropping Data

In [23]:
# Drop the Email column and store the result in a new variable.

df_no_email = df.drop('Email', axis=1)
df_no_email

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [ ]:
# Drop the row with index 2 in place.
df.drop(2, inplace=True)

In [27]:
df.head()

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [31]:
# Drop the City and Email columns, and assign the result back to df.
df = df.drop(['City', 'Email'], axis=1)

In [32]:
df.head()

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [35]:
# Drop the first and last row, and store the result in df_trimmed.
df_trimmed = df.drop([0, 3], axis=0)
df_trimmed

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

### Exercise 2: Missing Data

In [16]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [2]:
# View the first 5 rows of the DataFrame.
df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [ ]:
# Show where values are missing.
df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [5]:
# Count missing values by column.
df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

In [6]:
# Drop rows with missing data.
df.dropna()

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

In [8]:
# Drop columns with missing data.
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [15]:
# Fill missing Age values with the mean.
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000     NaN
3    David  40.000000   Miami
4      Eva  33.333333  Boston

In [24]:
# Fill missing City values with "Unknown".
df['City'] = df['City'].fillna('Unknown')
df

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

### Exercise 3: Duplicates

In [25]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [19]:
# Find which rows are duplicates across all columns.
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [21]:
# Drop duplicate rows, keeping the first occurrence.
df_cleaned = df.drop_duplicates()
df_cleaned

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

In [23]:
# Drop duplicate rows, keeping only the last occurrence.
df_cleaned = df.drop_duplicates(keep='last')
df_cleaned

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [26]:
# Drop all duplicates, removing both the original and duplicate rows.
df_cleaned = df.drop_duplicates(keep=False)
df_cleaned

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

## Section 3: Data Wrangling Essentials

In [4]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

### Exercise 1: Renaming Columns

In [2]:
# Change fname to FirstName and lname to LastName.
df.rename(columns={
    'fname': 'FirstName',
    'lname': 'LastName'
    }, inplace=True)
df

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [5]:
# Change all column names to: ['FirstName', 'LastName', 'Country']
df.columns = ['FirstName', 'LastName', 'Country']
df

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

### Exercise 2: Reordering Columns

In [16]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

In [18]:
# Rename Dept to Department and Sal to Salary.
df.rename(columns={
    'Dept': 'Department',
    'Sal': 'Salary'
}, inplace=True)
df

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [19]:
# Reorder columns so Salary appears first, followed by Name and Department.
df = df[['Name', 'Department', 'Salary']]
cols = df.columns.tolist()
new_order = [cols[-1]] + cols[:-1]  # Moves the last column to the front
df = df[new_order]

In [15]:
# Print the updated DataFrame.
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

### Exercise 3: GroupBy and Agg

In [2]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [ ]:
# Group the data by Store and use .agg() to find the average Sales and average Profit for each store.
df.groupby('Store')[['Sales', 'Profit']].mean()

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [7]:
# Group by Product and get the maximum Sales and minimum Profit.
df.groupby('Product').agg({
    'Sales': 'max',
    'Profit': 'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

In [9]:
# Group by Store and return the average Sales and maximum Profit, but name the columns Avg_Sales and Max_Profit.
df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

In [13]:
df.groupby(['Store', 'Product']).agg(sum)

               Sales  Profit
Store Product
A     Apples     100      30
      Bananas     90      20
      Oranges     80      25
B     Apples     120      40
      Bananas    110      35
C     Apples      95      32
      Bananas    160      40
      Oranges     60      15

### Exercise 4: Joining

In [20]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

df_cities = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago']
}, index=[101, 102, 103])

In [17]:
# Join df_orders to df_customers on the index.
result = df_customers.join(df_orders)
result

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [21]:
# Add a new column to df_customers with city data from df_cities.
result = pd.concat([df_customers, df_cities], axis=1)
result

    CustomerName     City
101        Alice      NYC
102          Bob       LA
103      Charlie  Chicago